spring:
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/spring_security
    username: parkhyeongju
    password: "!hyeongju@"

jwt:
  secret: "unvc/0IBfMVGKYNZa9xML9mhxBU8cactIVvVu7m6cmzZsW5dx+ncf6dBbMt3X/Wxu2cj0YaQnZCnmUch60TkKQ=="
  access-token-validity-ms: 900000
  refresh-token-validity-ms: 604800000