spring:
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/spring_security
    username: parkhyeongju
    password: "!hyeongju@"

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${MYAPP_KAKAO_CLIENT_ID}
            client-secret: ${MYAPP_KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
              - gender
              - age_range
              - birthday

          google:
            client-id: ${MYAPP_GOOGLE_CLIENT_ID}
            client-secret: ${MYAPP_GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - profile
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

jwt:
  secret: "unvc/0IBfMVGKYNZa9xML9mhxBU8cactIVvVu7m6cmzZsW5dx+ncf6dBbMt3X/Wxu2cj0YaQnZCnmUch60TkKQ=="
  access-token-validity-ms: 900000
  refresh-token-validity-ms: 604800000